### ISSUE TITLE
External link visual cue

### ISSUE THREAD

**Issue by eharkins** [nextstrain/sphinx-theme#3]
Something similar to nextstrain.org/docs' symbols which indicate an external link in the sidebar (and in a document, but especially in the sidebar) would be helpful:

![Screen Shot 2020-10-21 at 5 16 59 PM](https://user-images.githubusercontent.com/12140437/96803450-401a1880-13c1-11eb-9b8b-1dc9d3eead1f.png)

**Comment by tsibley** [comment]
This would be best implemented by a small amount of custom CSS in `lib/nextstrain/sphinx/theme/static/css/nextstrain.css`.
