### ISSUE TITLE
Install nextstrain.sphinx.theme extension downstream

### ISSUE THREAD

**Issue by victorlin** [nextstrain/sphinx-theme#30]
Upon seeing nextstrain/cli#198 I noticed we never leveraged #24 in practice across our docs projects.

- [x] [readthedocs-testbed](https://github.com/nextstrain/readthedocs-testbed): https://github.com/nextstrain/readthedocs-testbed/pull/1
- [x] [nextstrain.org](https://github.com/nextstrain/nextstrain.org): https://github.com/nextstrain/nextstrain.org/pull/574
- [x] [nextclade](https://github.com/nextstrain/nextclade): https://github.com/nextstrain/nextclade/pull/943
- [x] [cli](https://github.com/nextstrain/cli): nextstrain/cli#198
- [x] [auspice](https://github.com/nextstrain/auspice): https://github.com/nextstrain/auspice/pull/1535
- [x] [docs.nextstrain.org](https://github.com/nextstrain/docs.nextstrain.org): https://github.com/nextstrain/docs.nextstrain.org/pull/119
- [x] [augur](https://github.com/nextstrain/augur): https://github.com/nextstrain/augur/pull/1005
- [x] [ncov](https://github.com/nextstrain/ncov): https://github.com/nextstrain/ncov/pull/983

Doing this would also automatically enable any other extensions we install here in the future.

**Comment by tsibley** [comment]
Thanks for enumerating this before I got a chance to! Saved me some trawling. :-)

**Comment by victorlin** [comment]
This checks off the "tend to smaller issues/PRs" in my task list today!
